name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"   # 2. 确认你的 Node.js 版本
    
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
          
      - name: Install Dependencies
        run: npm install
    
      - name: Build Hexo
        run: npm run build   # 3. 如果构建命令不是 'npm run build' 则需修改
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.HEXO_DEPLOY_PAT }}
          repository-name: mengling02/mengling02.github.io   # 4. 改为你的 Pages 仓库
          branch: main
          folder: ./public   # 5. 如果生成的静态文件目录不是 'public' 则需修改
          commit-message: 'Automatically deployed by GitHub Actions'
